"use client";

import { useState } from "react";
import {
  API_BASE,
  autoGenerateDeliverable,
  pollDeliverable,
  saveDeliverable,
} from "@/lib/api";

const STATUS_LABEL: Record<string, string> = {
  routed: "In coda…",
  running: "Generazione in corso…",
  validating: "Controllo qualità (fonti, conformità)…",
};

/**
 * Flusso ufficiale: niente form. Il bot ha già raccolto i dati in chat (e dai file
 * caricati); qui c'è UN bottone che genera il documento via motore 8e con gli input
 * auto-compilati dalla conversazione, poi mostra il link al PDF.
 */
export function ReportGenerator({
  sessionId,
  getAuthToken,
}: {
  sessionId: string;
  getAuthToken?: () => Promise<string | null>;
}) {
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [label, setLabel] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  async function generate() {
    setBusy(true);
    setErr(null);
    setPdfUrl(null);
    setStatus("routed");
    try {
      const token = getAuthToken ? await getAuthToken() : null;
      const { job_id, label: lbl } = await autoGenerateDeliverable(sessionId, token);
      if (lbl) setLabel(lbl);
      const final = await pollDeliverable(job_id, (j) => setStatus(j.status));
      if (final.status === "rendered") {
        const saved = await saveDeliverable(sessionId, job_id, token);
        setPdfUrl(saved ?? `${API_BASE}/api/kbot/deliverables/${encodeURIComponent(job_id)}/pdf`);
      } else if (final.status === "refused") {
        setErr(
          "Non sono riuscito a generare il documento con i dati attuali. " +
            "Dammi qualche dettaglio in più in chat (o carica il bilancio) e riprovo.",
        );
      } else {
        setErr("Generazione non riuscita. Riprova.");
      }
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Errore");
    } finally {
      setBusy(false);
      setStatus(null);
    }
  }

  if (pdfUrl) {
    return (
      <div className="mt-4">
        <a
          href={pdfUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90"
        >
          Apri il report{label ? ` · ${label}` : ""} (PDF)
        </a>
        <span className="ml-3 text-xs text-[var(--text-muted)]">Salvato anche in Dashboard.</span>
      </div>
    );
  }

  return (
    <div className="mt-4 flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={generate}
          disabled={busy}
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90 disabled:opacity-60"
        >
          {busy ? "Generazione in corso…" : "Genera il report"}
        </button>
        {busy && (
          <span className="text-xs text-[var(--text-muted)]">
            {STATUS_LABEL[status ?? "routed"] ?? "Lavoro in corso…"} — può richiedere qualche minuto.
          </span>
        )}
      </div>
      {err && <p className="text-xs text-red-400">{err}</p>}
    </div>
  );
}
