"use client";

import { useState } from "react";
import {
  API_BASE,
  autoGenerateDeliverable,
  pollDeliverable,
  saveDeliverable,
  startBoostCheckout,
} from "@/lib/api";

const STATUS_LABEL: Record<string, string> = {
  routed: "In coda…",
  running: "Generazione in corso…",
  validating: "Controllo qualità (fonti, conformità)…",
};

/**
 * Flusso ufficiale: niente form. Il bot ha già raccolto i dati in chat (e dai file
 * caricati); qui c'è UN bottone che genera il documento via motore 8e con gli input
 * auto-compilati dalla conversazione, poi mostra il link al PDF.
 */
export function ReportGenerator({
  sessionId,
  getAuthToken,
}: {
  sessionId: string;
  getAuthToken?: () => Promise<string | null>;
}) {
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [label, setLabel] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [checkout, setCheckout] = useState<{ servizioId?: string; label?: string; prezzo?: number } | null>(null);

  async function unlock() {
    if (!checkout?.servizioId) return;
    setBusy(true);
    setErr(null);
    try {
      const token = getAuthToken ? await getAuthToken() : null;
      const url = await startBoostCheckout(sessionId, checkout.servizioId, token);
      window.location.href = url; // ritorno da Stripe → status=paid → ri-genera
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Errore checkout");
      setBusy(false);
    }
  }

  async function generate() {
    setBusy(true);
    setErr(null);
    setPdfUrl(null);
    setCheckout(null);
    setStatus("routed");
    try {
      const token = getAuthToken ? await getAuthToken() : null;
      const res = await autoGenerateDeliverable(sessionId, token);
      if (res.kind === "checkout") {
        setCheckout({ servizioId: res.servizio_id, label: res.label, prezzo: res.prezzo_eur });
        setBusy(false);
        return;
      }
      if (res.kind === "unavailable") {
        setErr(res.message);
        setBusy(false);
        return;
      }
      if (res.label) setLabel(res.label);
      const jobId = res.job_id;
      const final = await pollDeliverable(jobId, (j) => setStatus(j.status));
      if (final.status === "rendered") {
        const saved = await saveDeliverable(sessionId, jobId, token);
        setPdfUrl(saved ?? `${API_BASE}/api/kbot/deliverables/${encodeURIComponent(jobId)}/pdf`);
      } else if (final.status === "refused") {
        setErr(
          "Non sono riuscito a generare il documento con i dati attuali. " +
            "Dammi qualche dettaglio in più in chat (o carica il bilancio) e riprovo.",
        );
      } else {
        setErr("Generazione non riuscita. Riprova.");
      }
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Errore");
    } finally {
      setBusy(false);
      setStatus(null);
    }
  }

  if (pdfUrl) {
    return (
      <div className="mt-4">
        <a
          href={pdfUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90"
        >
          Apri il report{label ? ` · ${label}` : ""} (PDF)
        </a>
        <span className="ml-3 text-xs text-[var(--text-muted)]">Salvato anche in Dashboard.</span>
      </div>
    );
  }

  if (checkout) {
    const prezzo = checkout.prezzo ? ` · ${checkout.prezzo}€` : "";
    return (
      <div className="mt-4 flex flex-col gap-2">
        <button
          onClick={unlock}
          disabled={busy}
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90 disabled:opacity-60"
        >
          {busy ? "Apertura pagamento…" : `Sblocca il report${checkout.label ? ` · ${checkout.label}` : ""}${prezzo}`}
        </button>
        <span className="text-xs text-[var(--text-muted)]">
          Pagamento sicuro via Stripe. Dopo il pagamento il report viene generato automaticamente.
        </span>
        {err && <p className="text-xs text-red-400">{err}</p>}
      </div>
    );
  }

  return (
    <div className="mt-4 flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={generate}
          disabled={busy}
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90 disabled:opacity-60"
        >
          {busy ? "Generazione in corso…" : "Genera il report"}
        </button>
        {busy && (
          <span className="text-xs text-[var(--text-muted)]">
            {STATUS_LABEL[status ?? "routed"] ?? "Lavoro in corso…"} — può richiedere qualche minuto.
          </span>
        )}
      </div>
      {err && <p className="text-xs text-red-400">{err}</p>}
    </div>
  );
}
