"use client";

import { useEffect, useRef, useState } from "react";
import {
  API_BASE,
  autoGenerateDeliverable,
  demoPayBoost,
  type DeliverableJob,
  KBOT_FAKE_PAYMENT,
  pollDeliverable,
  saveDeliverable,
  startBoostCheckout,
} from "@/lib/api";

const GENERIC_REFUSAL =
  "Non sono riuscito a generare il documento con i dati attuali. " +
  "Dammi qualche dettaglio in più in chat (o carica il bilancio) e riprovo.";

// Etichette leggibili per i campi più comuni; per gli altri si prettifica l'id.
const FIELD_LABELS: Record<string, string> = {
  ragione_sociale: "la ragione sociale (nome azienda)",
  descrizione_azienda: "una breve descrizione dell'azienda",
  competitor: "i 2-3 competitor principali",
  obiettivo_strategico: "l'obiettivo strategico (cosa vuoi ottenere)",
  settore_ateco: "il settore/codice ATECO",
};

/** Estrae i NOMI dei campi mancanti dall'errore del Gate 0 8e ("campo: motivo; campo2: …")
 *  e li rende leggibili, così l'utente sa ESATTAMENTE cosa aggiungere. */
function namedMissingFields(error: string): string {
  const ids = error
    .split(/[;\n]/)
    .map((s) => s.split(":")[0].trim())
    .filter((s) => s && s.length <= 40 && !s.includes(" "));
  const labels = Array.from(new Set(ids)).map((id) => FIELD_LABELS[id] ?? id.replace(/_/g, " "));
  return labels.join(", ");
}

/** Messaggio LEGGIBILE per un job rifiutato: il motore 8e dice PERCHÉ (`refusal_reason` +
 *  `error`). Per i dati mancanti NOMINIAMO i campi (non più un generico "mancano dei dati"). */
function refusedMessage(job: DeliverableJob): string {
  const detail = (job.error ?? "").trim();
  if (job.refusal_reason === "insufficient_or_inconsistent_input") {
    const fields = namedMissingFields(detail);
    return fields
      ? `Per generare il documento mi servono ancora: ${fields}. Aggiungili in chat e premi di nuovo Genera.`
      : "Mancano dei dati necessari per questo documento. Aggiungili in chat e premi di nuovo Genera.";
  }
  const map: Record<string, string> = {
    grounding_failed:
      "Il controllo qualità ha bloccato contenuti non verificabili (numeri o fonti non confermati). " +
      "Dammi dati più concreti in chat e riprovo.",
    validation_failed:
      "Il documento generato non risultava completo o conforme. Riprova; se persiste, aggiungi dettagli in chat.",
    snapshot_stale:
      "Alcuni riferimenti normativi non sono aggiornati in questo momento. Riprova più tardi.",
  };
  const friendly = job.refusal_reason ? map[job.refusal_reason] : undefined;
  if (friendly) return friendly;
  return detail ? `Non sono riuscito a generare il documento: ${detail}` : GENERIC_REFUSAL;
}

const STATUS_LABEL: Record<string, string> = {
  routed: "In coda…",
  running: "Generazione in corso…",
  validating: "Controllo qualità (fonti, conformità)…",
};

/**
 * Flusso ufficiale: niente form. Il bot ha già raccolto i dati in chat (e dai file
 * caricati); qui c'è UN bottone che genera il documento via motore 8e con gli input
 * auto-compilati dalla conversazione, poi mostra il link al PDF.
 */
export function ReportGenerator({
  sessionId,
  getAuthToken,
  boostLabel,
}: {
  sessionId: string;
  getAuthToken?: () => Promise<string | null>;
  /** Nome del Boost che verrà generato — mostrato sul bottone così l'utente
   *  vede COSA sta per generare e può accorgersi di un routing sbagliato PRIMA
   *  di spendere la generazione (es. "LegalBoost DD" su una chat di marketing). */
  boostLabel?: string;
}) {
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [label, setLabel] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [checkout, setCheckout] = useState<{ servizioId?: string; label?: string; prezzo?: number } | null>(null);
  const [jobId, setJobId] = useState<string | null>(null);
  const resumedRef = useRef(false);

  // Rientro post-pagamento: page.tsx ha adottato la sessione paid e messo il flag
  // kbot.pay_resume=<session_id>. Qui riprendo la generazione da solo (il ponte
  // pagamento→report): l'utente paga, torna, e il report parte senza ri-cliccare.
  useEffect(() => {
    if (resumedRef.current) return;
    let flag: string | null = null;
    try { flag = sessionStorage.getItem("kbot.pay_resume"); } catch { flag = null; }
    if (flag && flag === sessionId) {
      resumedRef.current = true;
      try { sessionStorage.removeItem("kbot.pay_resume"); } catch { /* ignore */ }
      void generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  async function unlock() {
    if (!checkout?.servizioId) return;
    setBusy(true);
    setErr(null);
    try {
      const token = getAuthToken ? await getAuthToken() : null;
      if (KBOT_FAKE_PAYMENT) {
        // DEMO: pagamento simulato → la sessione diventa paid → rigenero subito.
        // Stessa identica catena della produzione, manca solo Stripe.
        await demoPayBoost(sessionId, checkout.servizioId, token);
        await generate();
        return;
      }
      const url = await startBoostCheckout(sessionId, checkout.servizioId, token);
      window.location.href = url; // ritorno da Stripe → status=paid → ri-genera
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Errore checkout");
      setBusy(false);
    }
  }

  async function generate() {
    setBusy(true);
    setErr(null);
    setPdfUrl(null);
    setCheckout(null);
    setStatus("routed");
    try {
      const token = getAuthToken ? await getAuthToken() : null;
      const res = await autoGenerateDeliverable(sessionId, token);
      if (res.kind === "checkout") {
        setCheckout({ servizioId: res.servizio_id, label: res.label, prezzo: res.prezzo_eur });
        setBusy(false);
        return;
      }
      if (res.kind === "unavailable") {
        setErr(res.message);
        setBusy(false);
        return;
      }
      if (res.label) setLabel(res.label);
      const jobId = res.job_id;
      setJobId(jobId);
      const final = await pollDeliverable(jobId, (j) => setStatus(j.status));
      if (final.status === "rendered") {
        const saved = await saveDeliverable(sessionId, jobId, token);
        setPdfUrl(saved ?? `${API_BASE}/api/kbot/deliverables/${encodeURIComponent(jobId)}/pdf`);
      } else if (final.status === "refused") {
        setErr(refusedMessage(final));
      } else if (final.error === "timeout") {
        // Il job NON è fallito: sul modello locale la generazione richiede più minuti
        // e il polling ha raggiunto il tetto. Prosegue lato server e arriva via email.
        setErr(
          "Il report richiede qualche minuto in più (documento completo su modello locale). " +
          "Resta su questa pagina o riaprila tra poco: appena pronto lo trovi qui, e ti arriva anche via email."
        );
      } else {
        setErr("Generazione non riuscita. Riprova.");
      }
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Errore");
    } finally {
      setBusy(false);
      setStatus(null);
    }
  }

  if (pdfUrl) {
    return (
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <a
          href={pdfUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90"
        >
          Apri il report{label ? ` · ${label}` : ""} (PDF)
        </a>
        {jobId && (
          <a
            href={`${API_BASE}/api/kbot/deliverables/${encodeURIComponent(jobId)}/xlsx`}
            className="inline-flex rounded-lg border border-[var(--teal)] px-4 py-2 text-sm font-semibold text-[var(--teal)] hover:bg-[var(--teal)]/10"
          >
            Scarica il modello (Excel)
          </a>
        )}
        <span className="text-xs text-[var(--text-muted)]">Salvato anche in Dashboard.</span>
      </div>
    );
  }

  if (checkout) {
    const prezzo = checkout.prezzo ? ` · ${checkout.prezzo}€` : "";
    const labelSuffix = `${checkout.label ? ` · ${checkout.label}` : ""}${prezzo}`;
    return (
      <div className="mt-4 flex flex-col gap-2">
        {KBOT_FAKE_PAYMENT && (
          <span className="inline-flex w-fit items-center rounded-full border border-amber-400/40 bg-amber-400/10 px-2 py-0.5 text-[11px] font-semibold text-amber-300">
            DEMO · pagamento simulato
          </span>
        )}
        <button
          onClick={unlock}
          disabled={busy}
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90 disabled:opacity-60"
        >
          {busy
            ? KBOT_FAKE_PAYMENT
              ? "Pagamento demo…"
              : "Apertura pagamento…"
            : `${KBOT_FAKE_PAYMENT ? "Paga in demo" : "Sblocca il report"}${labelSuffix}`}
        </button>
        <span className="text-xs text-[var(--text-muted)]">
          {KBOT_FAKE_PAYMENT
            ? "Pagamento simulato: nessun addebito reale. Dopo la conferma il report viene generato esattamente come in produzione."
            : "Pagamento sicuro via Stripe. Dopo il pagamento il report viene generato automaticamente."}
        </span>
        {err && <p className="text-xs text-red-400">{err}</p>}
      </div>
    );
  }

  return (
    <div className="mt-4 flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={generate}
          disabled={busy}
          className="inline-flex rounded-lg bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-black hover:opacity-90 disabled:opacity-60"
        >
          {busy ? "Generazione in corso…" : `Genera il report${boostLabel ? ` · ${boostLabel}` : ""}`}
        </button>
        {busy && (
          <span className="text-xs text-[var(--text-muted)]">
            {STATUS_LABEL[status ?? "routed"] ?? "Lavoro in corso…"} — può richiedere qualche minuto.
          </span>
        )}
      </div>
      {err && <p className="text-xs text-red-400">{err}</p>}
    </div>
  );
}
